// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(GridDbContext))]
    partial class GridDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.AvailablePower", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvailablePowerPlants")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DatetimeId")
                        .HasColumnType("int");

                    b.Property<int>("SubstationLineId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DatetimeId");

                    b.HasIndex("SubstationLineId");

                    b.ToTable("AvailablePowers");
                });

            modelBuilder.Entity("Domain.Entities.GridDatetime", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("AvailablePower")
                        .HasColumnType("real");

                    b.Property<DateOnly>("ForecastDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("ForecastTimestamp")
                        .HasColumnType("time");

                    b.Property<float>("RequiredPower")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("Datetimes");
                });

            modelBuilder.Entity("Domain.Entities.HourData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<TimeOnly>("ForecastTimestamp")
                        .HasColumnType("time");

                    b.Property<float>("ForecastedKw")
                        .HasColumnType("real");

                    b.Property<int>("PowerPlantDayId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PowerPlantDayId");

                    b.ToTable("HourDatas");
                });

            modelBuilder.Entity("Domain.Entities.Operator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Operators");
                });

            modelBuilder.Entity("Domain.Entities.OwnerDeal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("CompetionDeal")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ConclusionDeal")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumberPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LastModifiedAt");

                    b.ToTable("OwnerDeals");
                });

            modelBuilder.Entity("Domain.Entities.PowerPlant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateCommissioning")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("DateDecommissioning")
                        .HasColumnType("date");

                    b.Property<int>("DealId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MaxCapacityKw")
                        .HasColumnType("real");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubstationLineId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DealId");

                    b.HasIndex("LastModifiedAt");

                    b.HasIndex("SubstationLineId");

                    b.ToTable("PowerPlants");
                });

            modelBuilder.Entity("Domain.Entities.PowerPlantDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("ForecastDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("LastModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlantId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlantId");

                    b.ToTable("PowerPlantDays");
                });

            modelBuilder.Entity("Domain.Entities.Substation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("MaxThroughputMw")
                        .HasColumnType("real");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Substations");
                });

            modelBuilder.Entity("Domain.Entities.SubstationLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<float>("BaseLoadKw")
                        .HasColumnType("real");

                    b.Property<string>("LineName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SubstationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SubstationId");

                    b.ToTable("SubstationLines");
                });

            modelBuilder.Entity("Domain.Entities.AvailablePower", b =>
                {
                    b.HasOne("Domain.Entities.GridDatetime", "Datetime")
                        .WithMany()
                        .HasForeignKey("DatetimeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SubstationLine", "SubstationLine")
                        .WithMany("AvailablePowers")
                        .HasForeignKey("SubstationLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Datetime");

                    b.Navigation("SubstationLine");
                });

            modelBuilder.Entity("Domain.Entities.HourData", b =>
                {
                    b.HasOne("Domain.Entities.PowerPlantDay", "PowerPlantDay")
                        .WithMany("HourDatas")
                        .HasForeignKey("PowerPlantDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PowerPlantDay");
                });

            modelBuilder.Entity("Domain.Entities.PowerPlant", b =>
                {
                    b.HasOne("Domain.Entities.OwnerDeal", "Deal")
                        .WithMany("PowerPlants")
                        .HasForeignKey("DealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.SubstationLine", "SubstationLine")
                        .WithMany()
                        .HasForeignKey("SubstationLineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Deal");

                    b.Navigation("SubstationLine");
                });

            modelBuilder.Entity("Domain.Entities.PowerPlantDay", b =>
                {
                    b.HasOne("Domain.Entities.PowerPlant", "PowerPlant")
                        .WithMany("ForecastDays")
                        .HasForeignKey("PlantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PowerPlant");
                });

            modelBuilder.Entity("Domain.Entities.SubstationLine", b =>
                {
                    b.HasOne("Domain.Entities.Substation", "Substation")
                        .WithMany("SubstationLines")
                        .HasForeignKey("SubstationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Substation");
                });

            modelBuilder.Entity("Domain.Entities.OwnerDeal", b =>
                {
                    b.Navigation("PowerPlants");
                });

            modelBuilder.Entity("Domain.Entities.PowerPlant", b =>
                {
                    b.Navigation("ForecastDays");
                });

            modelBuilder.Entity("Domain.Entities.PowerPlantDay", b =>
                {
                    b.Navigation("HourDatas");
                });

            modelBuilder.Entity("Domain.Entities.Substation", b =>
                {
                    b.Navigation("SubstationLines");
                });

            modelBuilder.Entity("Domain.Entities.SubstationLine", b =>
                {
                    b.Navigation("AvailablePowers");
                });
#pragma warning restore 612, 618
        }
    }
}
